mui/mui-public

src/components/Webpagetests.js
src/pages/Landing.js

Adds a UI to create visual comparisons for PRs using webpagetest.org.

feat: Add convenience interface for webpage test

---

src/pages/Landing.js

Interesting since https://github.com/mui-org/material-ui/pull/22455

feat: Add azure pipelines monitor

---

src/pages/SizeComparison.js

The link for the comparison can be ready before the build is finished. For that short period we're now displaying a descriptive error.

fix: Add error boundary for when a build is not ready

---

package.json
src/App.js
src/components/ForkRibbon.js
src/components/Heading.js
src/components/Webpagetests.js
src/index.js
src/pages/Landing.js
src/pages/SizeComparison.js
yarn.lock

Update react-scripts to 4.0

---

src/pages/Landing.js

1. use `ol` where appropriate
1. document "fetch-until-found" pattern
1. fix duplicate key warning

Fix minor circleci workflow issues

---

.gitignore
README.md
functions/test-profile-artifacts.js
netlify.toml
package.json
src/App.js
src/pages/TestProfileAnalysis.js
yarn.lock

MVP UI for https://github.com/mui-org/material-ui/pull/23638
Example: https://deploy-preview-21--mui-dashboard.netlify.app/test-profile?buildNumber=198694
Part of  https://github.com/eps1lon/mui-contributor-dashboard/issues/22

Add UI for test_profile (MVP)

---

.gitignore
package.json
src/pages/TestProfileAnalysis.tsx
yarn.lock

Part of https://github.com/eps1lon/mui-contributor-dashboard/issues/22
Example: https://deploy-preview-25--mui-dashboard.netlify.app/test-profile?buildNumber=199327

Link to interactions for a render

---

src/App.js
src/pages/TestProfileAnalysis.tsx
yarn.lock

Part of https://github.com/eps1lon/mui-contributor-dashboard/issues/22

Make individual analysis linkable

---

src/pages/TestProfileAnalysis.tsx

Mainly trying to debug why the displayed timings don't differ between browsers in prod.

Display all timings on timing hover

---

functions/test-profile-artifact.js
functions/test-profile-details.js
src/pages/TestProfileAnalysis.tsx

1. Disable Cache-Control on netlify
Until https://community.netlify.com/t/netlify-function-responds-with-wrong-body/27138 is fixed
1. Re-validate fetch profiles less often

fix: Fetch correct test_profile runs

---

.github/workflows/main.yml
package.json
src/App.js
src/components/ForkRibbon.js
src/pages/Landing.js
src/pages/SizeComparison.tsx
yarn.lock

Also switching to emotion to have a single styling solution.

Bump Material-UI to 5.0.0-alpha.19

---

src/pages/TestProfileAnalysis.tsx

Using https://github.com/mui-org/material-ui/pull/24289 as a stress test

fix(test-profile): Consider invariant number of interactions between profile sessions

---

yarn.lock

Fixes https://github.com/advisories/GHSA-pp7h-53gx-mx7r

Bump netlify-cli

---

functions/test-profile-details.js
src/pages/TestProfileAnalysis.tsx

- explicitly handling pull/*
- rest is considered a push on a branch

feat(test-profile): Support jobs on arbitrary refs

---

src/pages/TestProfileAnalysis.tsx

Useful when comparing two or more profiles.

feat(test-profile): Reflect test profile label in page title

---

package.json
yarn.lock

Re-creation of https://github.com/mui-org/mui-contributor-dashboard/pull/57 which didn't trigger netlify for unknown reasons

chore: Bump react-scripts

---

src/pages/SizeComparison.tsx

Following https://github.com/mui-org/material-ui/pull/29609

fix: Update artifact server

---

src/pages/SizeComparison.tsx

Preview for https://github.com/mui-org/material-ui/pull/29876:  https://deploy-preview-66--mui-dashboard.netlify.app/size-comparison?circleCIBuildNumber=319701&baseRef=master&baseCommit=3c9396f7ac6288907fa85490dd86e80fc45efe0a&prNumber=29876

feat(size-comparison): Add support for CircleCI

---

src/pages/SizeComparison.tsx

Finalize migration by removing  the fallback bucket

[fix] Finish new bucket migration

---

README.md

Update repo name in README

---

tools-public/package.json
tools-public/toolpad.yaml
tools-public/toolpad/bundleSizeQueries.ts
tools-public/toolpad/components/Diff.tsx
tools-public/toolpad/components/Percent.tsx
tools-public/toolpad/queries.ts
tools-public/yarn.lock

From https://github.com/mui/mui-toolpad-examples

Add bundle size dashboard

---

tools-public/toolpad.yaml
tools-public/toolpad/bundleSizeQueries.ts

Accidentally got copied over from https://github.com/mui/mui-public/blob/785ee43b99f3304b85c232e8eb283bb483843f59/contributor-dashboard-legacy/src/pages/SizeComparison.tsx#L279

Remove console.log

---

tools-public/toolpad/components/Chart.tsx
tools-public/toolpad/pages/communityContributors/page.yml
tools-public/toolpad/pages/communityPRs/page.yml
tools-public/toolpad/pages/communityPerMonth/page.yml
tools-public/toolpad/resources/bundleSizeQueries.ts

Inspired by https://about.gitlab.com/handbook/marketing/community-relations/performance-indicators/#unique-wider-community-contributors-per-month, I have also set thresholds based on Next.js

Cover community contributions

---

tools-public/toolpad/pages/genderManagement/page.yml
tools-public/toolpad/resources/queryGender.ts

[tools] women in management

---

tools-public/yarn.lock

Upgrade `cpu-features` to hopefully fix some windows install issues

Update cpu-features transitive dependency

---

tools-public/package.json
tools-public/yarn.lock

Upgraded toolpad version, all apps working now.

---

tools-public/toolpad/pages/missingGitHubLabel/page.yml

Fix https://www.notion.so/KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c?pvs=4#0231c2f8e6924c6d856b9dcda6af99c1

[tool] Ignore draft PRs in GitHub issues/PRs with no labels

---

tools-public/toolpad/resources/functions.ts

Avoid injection attacks. cc @prakhargupta1

Use graphql parameters

---

render.yaml
tools-public/toolpad/pages/OverviewPage/page.yml

Added it to have a production app for the example linked in the Toolpad beta announcement blog.

render.yaml update

---

tools-public/yarn.lock

let's see what this does to the memory

Upgrade Toolpad

---

.circleci/config.yml

Changes motivated by https://github.com/mui/mui-public/pull/127 which should have broken the CI.

[core] Add the beginning of a CI

---

tools-public/devlake/README.md
tools-public/devlake/docker-compose.yml

Adds the basic devlake docker file

[core] added devlake file

---

tools-public/toolpad/pages/OverviewPage/page.yml
tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
tools-public/toolpad/pages/design_kits_issue_111/page.yml
tools-public/toolpad/pages/issueWithoutProductScope/page.yml
tools-public/toolpad/pages/needtriageNotAssigned/page.yml
tools-public/toolpad/pages/openIssuesWithoutLabels/page.yml
tools-public/toolpad/pages/openPRs/page.yml
tools-public/toolpad/pages/waitingForMaintainer/page.yml

Fix https://github.com/mui/mui-public/pull/139#issuecomment-1869097990
I noticed this in https://github.com/mui/mui-public/pull/136#issuecomment-1869067489, frustrated to hit the rate limit.
---
I saw a few more options to help with rate limiting:
- https://github.com/mui/mui-toolpad/issues/1196
- Disable refresh
- Use a different API, the one I use is rate limited at 10 reqs/min
- Deduplicate the query, I don't really need two requests.
I will see if this is enough, it's already x3 better.

[tools] Correctly provide GitHub API Token

---

render.yaml

See https://github.com/mui/mui-private/pull/363

[core] Move to preview environments

---

tools-public/package.json
tools-public/pnpm-lock.yaml

[tools] Upgrade dependencies

---

.github/workflows/reusable-add-reviewers-to-pr.yml

SRY, for some reason the linter did not catch that the secret cannot have a type property! 🤷🏼

[infra] removed type from secret

---

.github/workflows/reusable-add-reviewers-to-pr.yml

[infra] fixed URL params and secret token for gh CLI

---

render.yaml
tools-public/package.json
tools-public/pnpm-lock.yaml

Split #154 into a smaller change

[tools][core] Upgrade to pnpm v9

---

.github/workflows/scripts/addClosingMessage.js

As mentioned here: https://github.com/mui/mui-public/pull/178#discussion_r1731297406 I adjusted the map with the ids that make the most sense.
For x and toolpad we cannot determine the full scope based off of the issue alone.
Fixes #180

[infra] Adjust repository slug to product id mapping

---

.github/workflows/add-closing-message-to-issue.yml

workflows have to be at the root level of the `.github/wokflows` folder 🤷🏼

[infra] Fix workflow file location

---

.github/workflows/scripts/addClosingMessage.js

label removal will return a 404 which results in the job to fail, so check that before removing! 🤦🏼

[infra] Fix label removal

---

.github/workflows/scripts/issues/orderIdValidation.js

[infra] Added the secret request back into the script

---

.github/workflows/issues_order-id-validation.yml
.github/workflows/scripts/issues/orderIdValidation.js

script version does not work (yet) 👎🏼

[infra] Rollback to env var

---

pnpm-lock.yaml
tools-public/package.json

Propagate https://github.com/mui/mui-toolpad/pull/3757.
The goal is to fix https://platform.securityscorecard.io/#/scorecard/mui.com/issues/application_security/csp_no_policy_v2

[tools] Upgrade Toolpad Studio

---

contributor-dashboard-legacy/functions/circle-ci-artifacts.js
contributor-dashboard-legacy/functions/test-profile-artifact.js
contributor-dashboard-legacy/functions/test-profile-details.js
contributor-dashboard-legacy/package.json
contributor-dashboard-legacy/public/index.html
contributor-dashboard-legacy/public/manifest.json
contributor-dashboard-legacy/src/App.js
contributor-dashboard-legacy/src/components/ErrorBoundary.js
contributor-dashboard-legacy/src/components/ForkRibbon.js
contributor-dashboard-legacy/src/components/Heading.js
contributor-dashboard-legacy/src/components/Webpagetests.js
contributor-dashboard-legacy/src/index.css
contributor-dashboard-legacy/src/index.js
contributor-dashboard-legacy/src/pages/Landing.js
contributor-dashboard-legacy/src/pages/SizeComparison.tsx
contributor-dashboard-legacy/src/pages/TestProfileAnalysis.tsx
contributor-dashboard-legacy/tsconfig.json
package.json
pnpm-lock.yaml

Noticed this in #212. While am at it, I might as well do this. For people reviewing changes, it's two commits.

[core] Remove prettier duplication

---

.github/workflows/scripts/prs/detectTargetBranch.js

[infra] Fix rest endpoint

---

.github/workflows/scripts/prs/checkTargetBranchLabel.js
.github/workflows/scripts/prs/detectTargetBranch.js

quick fix to unblock the broken workflows!

[infra] Fix pull request rest endpoint in workflows

---

.github/workflows/prs_create-cherry-pick-pr.yml
.github/workflows/scripts/prs/detectTargetBranch.js

[infra] Fixes workflow by adding fetch depth to checkout

---

.github/workflows/prs_create-cherry-pick-pr.yml
.github/workflows/scripts/prs/detectTargetBranch.js

[infra] Fix for matrix array generation

---

.github/workflows/scripts/prs/detectTargetBranch.js

[infra] Fix array operation in cherry pick workflow

---

.github/workflows/issues_add-closing-message.yml
.github/workflows/issues_body-cleanup.yml
.github/workflows/issues_order-id-validation.yml
.github/workflows/prs_check-target-branch-label.yml
.github/workflows/prs_create-cherry-pick-pr.yml

I guess we want those to follow the coding styles, too.

[core] Follow coding style

---

.github/workflows/issues_body-cleanup.yml
.github/workflows/scripts/issues/bodyCleanup.js
.github/workflows/scripts/issues/titleCleanup.js

- added a new script to clean the issue title and add the correct product name
- changed the way the search keywords are being added: when none are found its not added

[infra] Issue title cleanup script and keywords improvement

---

.github/workflows/scripts/issues/titleCleanup.js

just a quick improvement to not run an update when its not needed!

[infra] Adds early return to issue title cleanup

---

tools-public/toolpad/pages/issuesWithoutLabels/page.yml

For https://www.notion.so/mui-org/KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c?pvs=4#0231c2f8e6924c6d856b9dcda6af99c1
Preview: https://mui-public-tools-public-pr-228.onrender.com/prod/pages/issuesWithoutLabels

[tools] Add Toolpad to repo we check missing labels against

---

.github/workflows/prs_create-cherry-pick-pr.yml

This filtering should be done where the workflow is getting called from, not here.

[infra] Update workflow target filtering

---

pnpm-lock.yaml
tools-public/package.json

This update will make the page title in the sidebar from bold to normal.

[tools-public] Update @toolpad/studio to v0.12.0

---

.github/workflows/prs_check-target-branch-label.yml
.github/workflows/prs_create-cherry-pick-pr.yml
.github/workflows/scripts/prs/detectTargetBranch.js

The inputs are `''` by default, so the check with `??` did return a "false positive".

[infra] Fix manual workflow trigger

---

.github/workflows/scripts/prs/detectTargetBranch.js

[infra] Fix workflow bug on default case (to master)

---

.github/workflows/prs_create-cherry-pick-pr.yml

added a change according to https://github.com/mui/mui-public/pull/272#discussion_r1950650441

[infra] Fix secrets assignment

---

.github/workflows/scripts/prs/checkTypeLabel.js

[infra] adds `release` to type labels

---

.github/workflows/prs_check-if-pr-has-type-label.yml
.github/workflows/scripts/prs/checkTypeLabel.js

re-enabled the commenting on the PR as well ... if that's still not working we might need to resort to other methods/actions.

[infra] Added 'docs' label to array

---

.github/workflows/scripts/prs/checkTypeLabel.js

adds an additional early return for the case the comment already exists

[infra] Fix duplicate comments on type label check workflow

---

package.json
pnpm-lock.yaml

I guess, why not.
https://github.com/pnpm/pnpm/releases

[core] Upgrade pnpm

---

.github/workflows/scripts/prs/checkTypeLabel.js

This pull request includes updates to the `checkTypeLabel.js` script to improve the handling of type labels and comments on pull requests. The most important changes include reorganizing the code to ensure comments are updated correctly and adding new logic to handle existing comments more effectively.
Improvements to comment handling:
* [`.github/workflows/scripts/prs/checkTypeLabel.js`](diffhunk://#diff-361998ca54b30aa96846c66027233605002330c9bcceaca8a419381e01658d7bL48-R65): Moved the initialization of `commentLines` to ensure it is properly reset before use.
* [`.github/workflows/scripts/prs/checkTypeLabel.js`](diffhunk://#diff-361998ca54b30aa96846c66027233605002330c9bcceaca8a419381e01658d7bL48-R65): Changed the logic to find an existing comment instead of checking if any comment …

[infra] Fix comment listing

---

.github/workflows/general_handle-stale-issues-and-prs.yml
.github/workflows/scripts/prs/checkTypeLabel.js

This was leaving a lot of comments on PRs that have no need for a comment creating a lot of noise for others

[infra] Fix multiple comments on type label workflow

---

tools-public/toolpad/resources/queryAbout.ts

Preview https://mui-tools-public-pr-305.onrender.com/prod/pages/muicomabout

[tools-public] Fix team priorization

---

render.yaml

Same as https://github.com/mui/mui-private/pull/846

[tools] Add healthCheckPath

---

tools-public/toolpad/pages/npmVersion/page.yml

[tools] Show % in versions

---

apps/code-infra-dashboard/netlify.toml

Act on https://github.com/mui/mui-public/pull/304#issuecomment-2843023788

[core] Improve Netlify ignore logic

---

apps/code-infra-dashboard/package.json
package.json

It seems that we don't need this at the leaf, we have a mono repo.

[core] Move engine to root

---

packages/bundle-size-checker/src/cli.js
packages/bundle-size-checker/src/types.d.ts

Default to suggested parallelism, allow override

[code-infra] Allow controlling worker concurrency

---

.github/workflows/publish.yml

`NODE_AUTH_TOKEN` is for https://github.com/actions/setup-node

[infra] Fix passing auth token to pnpm

---

packages/bundle-size-checker/src/renderMarkdownReport.js
packages/bundle-size-checker/src/renderMarkdownReport.test.js

Adressing https://github.com/mui/mui-public/pull/345#discussion_r2134764354
Format list with a table, remove the details, keep the link

[bundle-monitor] Use markdown table

---

.github/workflows/scripts/prs/checkTargetBranchLabel.js
packages/code-infra/package.json
packages/code-infra/src/eslint/testConfig.mjs

Addresses some of the comments from the previous PR #344

[code-infra] Infra package followup #344

---

apps/code-infra-dashboard/package.json
apps/tools-public/package.json
package.json
packages/babel-plugin-display-name/package.json
packages/babel-plugin-minify-errors/package.json
packages/babel-plugin-resolve-imports/package.json
packages/bundle-size-checker/package.json
packages/code-infra/package.json
packages/docs-infra/package.json
pnpm-lock.yaml

[infra] Sync dependencies

---

packages/code-infra/package.json
pnpm-lock.yaml
renovate/default.json

To mitigate the supply chain [attack](https://www.stepsecurity.io/blog/supply-chain-security-alert-eslint-config-prettier-package-shows-signs-of-compromise).

[infra] Bump eslint-config-prettier

---

.github/actions/ci-publish/action.yml
.github/workflows/ci-base.yml

Also added argument for passing post-build command. See https://github.com/mui/base-ui/pull/2258/files#r2220370152
See this in action [here](https://github.com/mui/mui-public/pull/404/files#diff-5e33e311056b2c2aa8e5a0a83263774c849396fa0b5fab47c837d0b653411076R43) and [here](https://github.com/mui/base-ui/pull/2258/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR41).

[infra] Add option to enable comment and compact url for pkg.pr.new

---

renovate.json

Dog-food our renovate preset and try out node.js versioning

[infra] Dog-food renovate preset

---

packages/code-infra/src/cli/cmdSetVersionOverrides.mjs
packages/code-infra/src/cli/pnpm.mjs

Update versions overrides to be able to handle any package.

[infra] use more generic --pkg instead of --react/--typescript

---

apps/code-infra-dashboard/src/pages/SizeComparison.tsx
packages/bundle-size-checker/src/formatUtils.js
packages/bundle-size-checker/src/renderMarkdownReport.js
packages/bundle-size-checker/src/renderMarkdownReport.test.js

- ~Forcing en-US seems more reliable for the CI~
- For the title, use https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b?source=copy_link#d8e9cfb2423c4f83844a9f29d2032e3f.

[code-infra] Polish bundle-size-checker tables

---

packages/code-infra/src/eslint/baseConfig.mjs

https://github.com/mui/mui-x/pull/19071
cc @michaldudak as this will require an override in base ui until refactored.

[code-infra] Disallow typescript namespaces

---

packages/code-infra/src/cli/index.mjs

https://github.com/mui/base-ui/pull/2538

[code-infra] Error on unrecognized commands

---

packages/bundle-size-checker/src/builder.js
pnpm-lock.yaml
test/bundle-size/bundle-size-checker.config.mjs
test/bundle-size/package.json

This was broken in https://github.com/mui/mui-x/pull/19289. The script made some incorrect assumptions about chunk naming in the manifest

[code-infra] Fix bundle size for BarChartPro

---

render.yaml

See the deployment error in this PR #616: https://dashboard.render.com/web/srv-d2otdoumcj7s73ehuk1g/deploys/dep-d2otk6ndiees73cupvpg?r=2025-08-29%4016%3A48%3A31%7E2025-08-29%4016%3A50%3A41
It was broken with #552.

[tools] Fix Node.js version

---

.github/workflows/publish.yml

Fix https://github.com/mui/mui-public/security/code-scanning/51.

[internal] Fix action alert

---

apps/tools-public/toolpad/pages/muicomabout/page.yml
apps/tools-public/toolpad/resources/queryAbout.ts

For https://www.notion.so/mui-org/Leadership-aadebd80c39441ec876ae9dd392c48ec?source=copy_link#d088fe4cb5b34788a62cc493df28c44f

[tools] Add support for acting role

---

packages/code-infra/package.json
packages/code-infra/src/markdownlint/duplicate-h1.mjs
packages/code-infra/src/markdownlint/git-diff.mjs
packages/code-infra/src/markdownlint/index.mjs
packages/code-infra/src/markdownlint/straight-quotes.mjs
packages/code-infra/src/markdownlint/table-alignment.mjs
packages/code-infra/src/markdownlint/terminal-language.mjs
pnpm-lock.yaml

One step closer to removing @mui/monorepo

[infra] Migrate markdownlint config to code-infra

---

renovate/default.json

To avoid potential supply-chain attacks

[code-infra] Disable automerge for GitHub Actions

---

apps/code-infra-dashboard/src/App.tsx
apps/code-infra-dashboard/src/index.css

Just to get an upper bound on the width, also put some spacing between the header link and the content

[code-infra] Add Container to infra dashboard

---

apps/code-infra-dashboard/package.json
apps/tools-public/package.json
package.json
packages/babel-plugin-resolve-imports/package.json
packages/docs-infra/package.json
pnpm-lock.yaml

Downgraded all @types/node version to 22.18.3

[code-infra] Cleanup unused packages

---

renovate/README.md

Trying to preserve the knowledge.

[code-infra] Document renovatebot findings

---

apps/code-infra-dashboard/src/App.tsx
apps/code-infra-dashboard/src/components/FileDiff.tsx
apps/code-infra-dashboard/src/components/PRList.tsx
apps/code-infra-dashboard/src/hooks/useFileFilter.ts
apps/code-infra-dashboard/src/pages/DiffPackage.tsx
apps/code-infra-dashboard/src/pages/RepositoryCharts.tsx
apps/code-infra-dashboard/src/pages/RepositoryLayout.tsx
apps/code-infra-dashboard/src/pages/RepositoryPR.tsx
apps/code-infra-dashboard/src/pages/RepositoryPRs.tsx
packages/bundle-size-checker/src/cli.js
packages/bundle-size-checker/src/constants.js
packages/bundle-size-checker/src/renderMarkdownReport.js

* Add hash links for the files
* Reduce amount of dom by grouping lines with the same styles together
* Move filter field on its own line
* Clean up suspense boundaries in router
* Fix title nesting creating duplicate h1s
* Add link to PR dashboard in bundle size PR comment
[example](https://deploy-preview-718--mui-frontend-public.netlify.app/diff-package?package1=https://pkg.pr.new/mui/mui-public/@mui/internal-code-infra@3ba4fe1&package2=https://pkg.pr.new/mui/mui-public/@mui/internal-code-infra@8d4dde8)

[code-infra] Package diff tool tweaks

---

.github/actions/ci-publish/action.yml
.github/workflows/ci-base.yml

Closes https://github.com/mui/mui-public/issues/760
Adds a simple retry loop around the pkg.pr.new command

[code-infra] Add retry loop around continuous releases

---

.github/workflows/publish.yml
CHANGELOG.md
package.json
packages/code-infra/src/cli/cmdPublish.mjs
packages/code-infra/src/cli/cmdPublishCanary.mjs
packages/code-infra/src/cli/pnpm.mjs

This will be necessary for when releasing legacy versions

[code-infra] Support setting a dist tag for publishing packages

---

packages/code-infra/README.md
packages/code-infra/package.json
packages/code-infra/src/cli/cmdPublish.mjs
packages/code-infra/src/cli/cmdPublishNewPackage.mjs
packages/code-infra/src/cli/index.mjs
packages/code-infra/src/cli/pnpm.mjs
pnpm-lock.yaml

and throw an error with documentation link to fix the issue manually before publishing again.
Closes #737

[code-infra] Check for new packages in publish cli
