mui/mui-public

src/components/Webpagetests.js, src/pages/Landing.js
Need to test fetches on deploy previews more thoroughly. Fetching mixed content on localhost is fine but not on prod.
=> fix: Call webpagetest API over https

src/pages/SizeComparison.js
Fixes an issue reported in https://github.com/mui-org/material-ui/pull/21574#issuecomment-649840750
Edit:
Fixed: https://deploy-preview-9--mui-dashboard.netlify.app/size-comparison?buildId=10610&baseRef=next&baseCommit=57322a9c0ce51b3fc841216eaa7ae7d7d8da0f70&prNumber=21574
/cc @oliviertassinari
=> fix: merge base is the previous size

src/pages/Landing.js
Display workflow introduced in https://github.com/mui-org/material-ui/pull/23475 and also the main workflow for `next`.
=> feat(workflows): Display timezone tests and next pipeline

functions/test-profile-artifacts.js
Downloading all artifacts in the function can take a long time which means the actual response time is of the UI is slow. But once they're downloaded the response doesn't change since CircleCI builds and artifacts are immutable. The response should reflect that so the browser can cache it accordingly.
Part of #23
TODO: "Just" proxy artifact downloads. The current approach does not scale with the number of artifacts since netlify has a limit on the response size. We'll move this to the client (get a list of artifacts, request download for each). Should still be fast and we can re-use the caching approach and gzip it.
=> Cache the batched artifacts more aggressively

functions/test-profile-details.js, src/pages/Landing.js, src/pages/SizeComparison.tsx, src/pages/TestProfileAnalysis.tsx
Github org got renamed over the weekend.
Left azure urls as they are as they don't seem to have updated. (Not sure where we use those either)
=> Fix non-accessible urls

tools-public/package.json, tools-public/toolpad.yaml, tools-public/yarn.lock
Mark all embedded pages as "standalone"
=> Upgrade toolpad

tools-public/toolpad/pages/validateSupport/page.yml
Latest toolpad (0.1.18) passes the error from a query to the text field if the field is using the query data. This makes error checks like these unnecessary
=> Propagate errors from the backend automatically

render.yaml, tools-public/package.json
On top of the changes of https://github.com/mui/mui-toolpad/pull/2379 I'm able to get a 30% decrease in memory for free by avoiding `yarn run` and calling the script directly (on the datagrid example).
_Note: the graph is on top of the changes of https://github.com/mui/mui-toolpad/pull/2379, which already decreased memory by 50%. So the decrease in memory compared to the actual state will be more around 15%._
=> Replace yarn run and call the script directly

render.yaml
Avoid the startup of an unnecessary Node.js process to enable this flag by presetting it
=> Improve memory usage further

tools-public/package.json, tools-public/yarn.lock
I had removed `recharts` but it's still being used in the `PieChart` custom component, sorry.
=> Re-add recharts

tools-public/toolpad/pages/communityCore/page.yml, tools-public/toolpad/resources/functions.ts
Things done in the PR:
- fixed the community vs maintainers PR count
- added multi-line charts for the data in the data grid - it allows better representation for me
- added new joiners, removed people that left the team
Things that can be considered:
- adding charts based on the data grid data can likely be simplified, for e.g. I needed to manually add the lines on the charts <img width="300px" src="https://github.com/mui/mui-public/assets/4512430/1d3dea57-950b-43f2-9f50-48c37d064da9" /> 
it would have been much simpler if I was able to just choose the dimension "reviewed_by" and it would do everything for me - likely suited as a feature request for the X team - cc @joserodolfofreitas 
- the new lines were altering between only two colors, I needed to manually change the colors - we …
=> [tools] Update the core community dashboard

tools-public/toolpad/pages/waitingForMaintainer/page.yml
This moves the metric `needTriage` to a new name `waitingForMaintainer` and changes the label that has been searched for to `"status: waiting for maintainer"` accordingly
@Janpot could you add the redirect as discussed earlier today? Thanks!
=> [core] Rename `needTriage` to `waitingForMaintainer` and change search param

.github/ISSUE_TEMPLATE/1.bug.yml, .github/ISSUE_TEMPLATE/2.feature.yml, .github/ISSUE_TEMPLATE/3.rfc.yml, .github/workflows/ensure-triage-label.yml, .github/workflows/mark-duplicate.yml, .github/workflows/no-response.yml, tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml, tools-public/toolpad/pages/issueWithoutProductScope/page.yml, tools-public/toolpad/pages/needtriageNotAssigned/page.yml
Addresses point # 4 of https://github.com/mui/mui-x/issues/10810
Just before merging this PR, the GitHub label `status: needs more information` should be renamed to `status: waiting for author`, and a new label `status: waiting for maintainer` should be created.
=> [core] Update `no-response` workflow

tools-public/toolpad/pages/OverviewPage/page.yml, tools-public/toolpad/pages/needtriageNotAssigned/page.yml
Update the labels to be more accurate, related to https://github.com/mui/mui-x/issues/10810.
https://tools-public.mui.com/prod/pages/needtriageNotAssigned
=> [tools] Update app title

render.yaml
~PR previews don't expire. We've been paying 25$ per month for the last six month for a stale PR: https://github.com/mui/mui-public/pull/121.~
~This PR moves us to preview which does expire after 3 days, and which should have the same implications as PR previews since we all our services were using PR previews and we don't have anything else~
Moving the service to the starter plan. Waiting with the preview env changes as I didn't take into account they don't respect the rootDir setting the same way PR previews do
=> [tools] Move render.com services to the starter plan

tools-public/package.json, tools-public/pnpm-lock.yaml, tools-public/toolpad/application.yml, tools-public/toolpad/components/PieChart.tsx, tools-public/toolpad/pages/npmVersion/page.yml
I was curious to see how we stack up compared to Recharts. A big reason why MUI X Charts should exist is the belief that work on Recharts deserves to be carried on going forward, but it's not happening. So for this to happen, the migration experience should be easy.
Before: https://tools-public.mui.com/prod/pages/npmVersion?package=next
https://github.com/mui/mui-public/assets/3165635/85eab4d1-26f2-4aae-a999-8280934632fc
After: https://mui-publictools-public-mui-public-pr-147.up.railway.app/prod/pages/npmVersion?package=next
https://github.com/mui/mui-public/assets/3165635/77e7ca04-4d06-4600-9d4a-6c567d6a7150
=> [tools] Migrate from recharts to MUI X Charts

.github/workflows/reusable/add-closing-message-to-issue.yml, .github/workflows/scripts/addClosingMessage.js, package.json, pnpm-lock.yaml
This introduces reusable workflows to the org.
First one is the closing message as it is the first we can use in the core repo.
This PR should also fix sending this message on issues from the maintainers as well.
See https://github.com/mui/mui-private/issues/360
=> [infra] Create reusable workflows

pnpm-lock.yaml, tools-public/package.json
Not needed, already defined at the root of the workspace:
https://github.com/mui/mui-public/blob/8b6453a35df15e082e0368a1b240bbcc95c63737/package.json#L40-L43
=> [tools] Fix duplicate nested pnpm mention

.github/workflows/scripts/issues/addClosingMessage.js
This would allow the comment to take one less line, e.g. https://github.com/mui/material-ui/issues/43700#issuecomment-2352765908, making it denser hence faster to read.
I noticed this from https://github.com/mui/toolpad/pull/4076. Related to #183.
=> [infra] Shorten CSAT message

.github/workflows/scripts/issues/addClosingMessage.js
I'm following up on https://github.com/mui/mui-public/pull/203#issuecomment-2358020779. With the extra weeks of data, it now looks clear that the new notification message converts a lot less. See https://tally.so/forms/w4r5Mk/submissions. 0 feedback for x in September vs. 11 in August.
This PR restores the previous message, I don't see why we changed it, I resonate a lot more with the previous message template, e.g. https://github.com/mui/mui-x/issues/14291#issuecomment-2317907184.
I have also updated the link to feels more official: https://tally.mui.com/support-satisfaction-survey.
=> [infra] Improve CSAT engagmenet message

tools-public/toolpad/pages/bundleSizes/page.yml
I got frustrated with the UX of the table while working on https://github.com/mui/material-ui/pull/44075.
Before: https://tools-public.mui.com/prod/pages/bundleSizes?circleCIBuildNumber=759455&baseRef=master&baseCommit=a25a365a4c66738f358ecd745bf3727c0ca9d5b6&prNumber=44075
After: https://mui-public-tools-public-pr-211.onrender.com/prod/pages/bundleSizes?circleCIBuildNumber=759455&baseRef=master&baseCommit=a25a365a4c66738f358ecd745bf3727c0ca9d5b6&prNumber=44075
Side notes:
- It's impossible to search because of the virtualization: https://github.com/mui/mui-x/issues/5082
- Density mode feels wrong: https://github.com/mui/toolpad/issues/4242
- There is no way to have a full height data grid, so I went with having a larger height.
=> [code-infra] Improve display of bundle size diff

.github/workflows/scripts/issues/addClosingMessage.js
Closes https://github.com/mui/toolpad/issues/4261
It could be improved with:
* check and error if it can't find a productId
* pass product ID as a variable instead from the repo instead
=> Rename Toolpad repo

.github/workflows/prs_check-target-branch-label.yml, .github/workflows/scripts/prs/checkTargetBranchLabel.js, .github/workflows/scripts/prs/detectTargetBranch.js
Add the new reusable workflow to check the existence of target labels on PRs with "needs cherry-pick" label
=> [infra] Adds reusable workflow "check target branch label"

.github/workflows/prs_create-cherry-pick-pr.yml, .github/workflows/scripts/prs/detectTargetBranch.js
This handles 2 things:
1. switches to a matrix approach to prevent consecutive PRs being opened. Now this workflow will not run a number of times for each PR merged, but rather once opening several cherry-pick PRs at once (if multiple targets are needed)
2. add the reviewers from the original PR to the cherry-pick PR to improve workflow even more
=> [infra] Improve cherry-pick workflow

.github/workflows/scripts/prs/detectTargetBranch.js
Added a way of getting the approving reviewers (even when they are not in the set of requested reviewers) to the cherry-pick PR.
This also introduces a change that will still create a PR to master when the branch merged to is a version branch!
=> [infra] Request review from approving reviewers as well

.github/workflows/scripts/prs/detectTargetBranch.js
I guess we need this to be able to replace https://github.com/mui/material-ui/pull/41742.
=> [infra] Support other repo with cherry-pick workflow

.github/workflows/prs_create-cherry-pick-pr.yml
I noticed this in #244, this permission seems wrong, I imagine GitHub Actions tokens works the same way as https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
I actually don't know if this even has an impact here, so going for: https://github.com/mui/mui-x/pull/15456.
=> [infra] Remove cherry-pick issue write permission

tools-public/toolpad/pages/npmVersion/page.yml
Before:
After:
https://mui-public-tools-public-pr-253.onrender.com/prod/pages/npmVersion
=> [tools] Link to the right npm page

tools-public/toolpad/pages/muicomabout/page.yml, tools-public/toolpad/resources/queryAbout.ts
This helps to keep https://www.notion.so/mui-org/XXX-s-onboarding-c980eff81a1e405bb36476d0cf22b5e6?pvs=4#9e8f853698cd4a819ea5cdcb33c588f5 up to date.
Before: https://tools-public.mui.com/prod/pages/muicomabout
After: https://mui-public-tools-public-pr-254.onrender.com/prod/pages/muicomabout
This is used in https://github.com/mui/material-ui/blob/9057a52a6a229ef710bd324882b9d2be1a49b01f/docs/src/components/about/Team.tsx#L25
=> [tools] Improve the about export

tools-public/toolpad/pages/overdueRatio/page.yml
Improve this iframe:
https://www.notion.so/mui-org/KPIs-Finance-165cbfe7b66080ec8ac3cf9d616518df?pvs=4#165cbfe7b660803b8009c7b0a26a6675
1. Sync error threshold with https://www.notion.so/mui-org/KPIs-Finance-165cbfe7b66080ec8ac3cf9d616518df?pvs=4#165cbfe7b6608084b2deeab53843ef7e. I guess 10% is OK.
2. Now, it feels like we are always most of the time much below so we can tidy up the warning range.
=> [infra] Reduce Overdue ratio thresholds

.github/workflows/prs_create-cherry-pick-pr.yml, .github/workflows/scripts/prs/detectTargetBranch.js
This should allow us to call cherry pick automation with a dispatch call as well as pr merged.
I didn't opt to have a "on tag added" trigger, because it could re-trigger previously created cherrypicks if the PR had any. Making it manual is intentional
> Untested 😆 
Example of code on MUI-X
```yaml
name: Create cherry-pick PR
on:
pull_request_target:
branches: [master, next, 'v[0-9]+.x']
types: [closed]
workflow_dispatch:
inputs:
target_branch:
description: 'A target branch passed from the caller workflow'
required: true
type: string
pr_number:
description: 'The PR number to cherry-pick from'
required: true
type: string
permissions: {}
jobs:
create_pr:
name: Create cherry-pick PR
uses: mui/mui-public/.github/workflows/prs_create-cherry-pick-pr.yml@master
permissions:
contents: write …
```
=> [code-infra] Allow manual cherry pick inputs

tools-public/toolpad/pages/muicomabout/page.yml, tools-public/toolpad/resources/queryAbout.ts
Comes alongside of https://github.com/mui/material-ui/pull/45165. Now, we should be able to have a script that automatically pull the data from HiBob and store it in git to be displayable. This scale.
Preview: https://mui-public-tools-public-pr-268.onrender.com/prod/pages/muicomabout
=> [tools] Polish team export

render.yaml, tools-public/toolpad/pages/OverviewPage/page.yml
The build is broken: https://dashboard.render.com/web/srv-cgd3k7ceoogljtstv01g/deploys/dep-cuhncfdumphs73fn17ig?r=2025-02-05%4014%3A30%3A26%7E2025-02-05%4014%3A32%3A36.
See for context on what went wrong: https://github.com/pnpm/pnpm/issues/9029.
=> [tools] Fix render deploy

.github/workflows/prs_create-cherry-pick-pr.yml
I noticed on https://github.com/mui/material-ui/pull/45226 that the GitHub Actions didn't trigger:
Looking closer, I can link this back to a limitation that GitHub has to limit circular dependencies of actions https://github.com/orgs/community/discussions/55906. 
MUI X doesn't fall into this case, but Material UI does.
Oh ok, it's another to do it: https://github.com/mui/material-ui/pull/45100/commits, push extra commits, not great DX though.
My thought is that we can use https://www.notion.so/mui-org/Accounts-945f0ccb9f7749ccb9e84b9eb9b13ec7?pvs=4#5939440218e844b982761a0634b3b992 create a PAT, and use that for Material UI.
=> [code-infra] Support running GitHub Actions with cherry-pick

.github/workflows/prs_check-if-pr-has-type-label.yml, .github/workflows/scripts/prs/checkTypeLabel.js
This pull request introduces a new GitHub Actions workflow and a supporting script to ensure that pull requests have appropriate type labels. The most important changes include the creation of the workflow file and the implementation of the script to check for type labels.
New workflow for checking PR type labels:
* [`.github/workflows/prs_check-if-pr-has-type-label.yml`](diffhunk://#diff-adcf5b5fffef44caa3ceff40940b89c3870a96429acef30fb876e316b733bbc1R1-R31): Added a new workflow to check if pull requests have appropriate type labels. This workflow runs on a PR event and uses the `actions/checkout` and `actions/github-script` actions to execute the label checking script.
Implementation of the label checking script:
* [`.github/workflows/scripts/prs/checkTypeLabel.js`](diffhunk://#diff-361 …
=> [infra] Enforce type labels on PRs

.github/workflows/prs_check-if-pr-has-type-label.yml
This pull request includes a change to the GitHub Actions workflow configuration to rename a job and adjust its permissions.
Workflow configuration updates:
* [`.github/workflows/prs_check-if-pr-has-type-label.yml`](diffhunk://#diff-adcf5b5fffef44caa3ceff40940b89c3870a96429acef30fb876e316b733bbc1L9-L13): Renamed the job from `detect_cherry_pick_target` to `check_type_label` and removed the `issues: write` permission.
=> [infra] Fix workflow permission

.github/workflows/scripts/issues/addClosingMessage.js
Related to https://github.com/mui/mui-x/issues/16655#issuecomment-2673113182 and .
Add a check to ensure feedback requests are targeted at issues from paying customers with specific support plans. This change helps focus survey prompts on users with commercial support, improving feedback relevance.
I am not so sure if we should ditch the feedback from community members all together ... it feels wrong and we do get valuable feedback from them. On the other hand I am curious if this will increase conversion rate though. 🤷🏼 
Help with #156.
=> [infra] Enhance closing message logic for customer feedback

.github/workflows/scripts/issues/addClosingMessage.js
This pull request includes a minor change to the `addClosingMessage.js` script in the GitHub workflows. The change updates the property used to access issue labels to ensure the correct data is being referenced.
* [`.github/workflows/scripts/issues/addClosingMessage.js`](diffhunk://#diff-49c99cf6a373f8f1c4914a6873976f1e72230993ebc15ae6d934222646d66868L45-R45): Modified the `isPaidSupport` variable to access `issue.data.labels` instead of `issue.labels`.
=> [infra] Fix the closing message workflow

.github/workflows/scripts/prs/checkTypeLabel.js
This pull request includes several changes to the `checkTypeLabel.js` script to enhance its functionality and improve its handling of multiple type labels in pull requests. The most important changes include removing an unnecessary type label, adding logic to check for existing comments about multiple type labels, and exiting gracefully if such a comment is already present.
Enhancements to `checkTypeLabel.js` script:
* Removed the `'docs'` type label from the `typeLabels` array, as it is no longer needed.
* Added logic to find existing comments that mention multiple type labels in the `prComments` array.
* Implemented a check to exit gracefully if a comment about multiple type labels is already present, preventing duplicate comments.
=> [infra] Fix multiple comments issue

.github/workflows/prs_create-cherry-pick-pr.yml
changed the branch name format to make them unique in matrix runs. Previously, when creating multiple cherry-pick branches it was trying to create branches with the same name and failed
Came up in https://github.com/mui/mui-x/pull/17051
=> [infra] Changed branch name format

.github/workflows/general_handle-stale-issues-and-prs.yml
This pull request introduces a new GitHub Actions workflow to automatically manage stale issues and pull requests. The workflow is designed to label and close issues and pull requests that have been inactive for a specified period.
It is ment to be used with a CRON job on the repos. 
I plan to also add a manual trigger (at least for the first few days) to run this occasionally to mark and close old PRs and issues!
On a side note: I changed the threshold times we previously discussed.
Key changes:
* Added a new GitHub Actions workflow file `.github/workflows/general_handle-stale-issues-and-prs.yml` to handle stale issues and pull requests.
* Issues will be labeled as "stale" after 7 days of inactivity and closed after an additional 5 days if no activity occurs.
* Pull requests will be …
=> [infra] Added workflow to handle stale issues and PRs

.github/workflows/general_handle-stale-issues-and-prs.yml
This pull request includes updates to the `.github/workflows/general_handle-stale-issues-and-prs.yml` file to make the workflow more flexible and accurate. The most important changes include adding an input parameter for the number of operations and modifying the label used for identifying stale issues.
Enhancements to workflow flexibility and accuracy:
* [`.github/workflows/general_handle-stale-issues-and-prs.yml`](diffhunk://#diff-86a66f90da56f7c560ad4538035cc569747092cb2bb1de111acb8786da2dc175R4-R9): Added an input parameter `operations` to allow customization of the number of operations per run, with a default value of 50.
* [`.github/workflows/general_handle-stale-issues-and-prs.yml`](diffhunk://#diff-86a66f90da56f7c560ad4538035cc569747092cb2bb1de111acb8786da2dc175L16-R31): Updated …
=> [infra] Adds input to manually define operations

.github/workflows/issues_status-label-handler.yml
This pull request includes a change to the `.github/workflows/issues_status-label-handler.yml` file to update the permissions for the GitHub Actions workflow.
The actions permission is needed to delete the previous cache and create a new one, since the cache is immutable.
Permissions update:
* [`.github/workflows/issues_status-label-handler.yml`](diffhunk://#diff-0e8116178c69425e164d76127840e07db2db819a957b9c573dd946f2187551a7R15): Added `actions: write` permission to the `permissions` section.
=> [infra] Grants write permissions for actions

.github/workflows/issues_status-label-handler.yml
This pull request includes a small change to the `.github/workflows/issues_status-label-handler.yml` file. The change adds a condition to check if the event is not a pull request before proceeding with the job. 
* [`.github/workflows/issues_status-label-handler.yml`](diffhunk://#diff-0e8116178c69425e164d76127840e07db2db819a957b9c573dd946f2187551a7R12): Added a condition to check if the event is not a pull request (`if: ${{ !github.event.issue.pull_request }}`).
=> [infra] Add condition to skip comment check for pull requests

.github/workflows/general_handle-stale-issues-and-prs.yml
Review remarks from @oliviertassinari about the [top-level action permissions](https://github.com/mui/mui-public/pull/288#discussion_r2019792828) (thanks for pointing that out) and the [pinned version](https://github.com/mui/mui-public/pull/288#discussion_r2020273621) of the `actions/stale` action.
=> [infra] Update stale action version and add permissions section

.github/workflows/scripts/issues/statusLabelHandler.js
- added a new early return
- moved one early return up to prevent unnecessary execution
- trimmed down logic to only call update once, when needed
- removed the 'reopening' path
=> [infra] Refactor status label handling

.github/workflows/scripts/issues/statusLabelHandler.js
If we are not waiting for the author feedback (e.g. it is in the board already) we can exit the  execution early
=> [infra] Added new exit path

.github/workflows/scripts/issues/statusLabelHandler.js
Fixes failing workflow runs when the payload for commenting is not present (e.g. when closing the issue)
=> [core] Enhance debugging and author validation in status label handler

apps/code-infra-dashboard/public/_headers
I'm amazed that Vite has no docs for this: https://github.com/vitejs/vite/blob/1fe07d3716012992dd7b2e78d8380add0b606a97/docs/public/_headers#L1; but 🤷‍♂️
Preview: https://deploy-preview-333--mui-frontend-public.netlify.app/size-comparison/mui/material-ui/diff?circleCIBuildNumber=826971&baseRef=master&baseCommit=52ceb5804c12eaf401c033433afc72d3ee88bd5c&prNumber=46176
and it works: https://deploy-preview-333--mui-frontend-public.netlify.app/assets/index-oW5KvyZt.js.
=> [core] Set caching headers for mui-frontend-public

packages/bundle-size-checker/package.json, packages/bundle-size-checker/src/cli.js, packages/bundle-size-checker/src/configLoader.js, packages/bundle-size-checker/src/worker.js, pnpm-lock.yaml
Allow JSX and TS in custom bundle scripts. Also add a method for resolving package.json files in case no `/package.json` export is available and the user is on node 22.14+.
Confirmed in base ui that this allows for entries such as
```tsx
{
id: 'custom',
code: `
import { Field } from '@base-ui-components/react/field';
export default <>
<Field.Root />
<Field.Label />
</>
`,
externals: ['react', 'react-dom'],
}
```
=> [code-infra] Support JSX and TS in bundle scripts

update-netlify-ignore.js
The script would silently succeed if someone accidentally removed the ignore line from netlify.toml.
Need to do it this way because the end result will most of the time be identical to the input
=> [code-infra] Add sanity check that replacement has actually happend

.github/workflows/scripts/prs/checkTypeLabel.js
* Removed the `createCommentHandler` function and its associated logic for managing comments on pull requests. The script now directly sets the workflow status without adding explanatory comments to pull requests. 
* Simplified error handling by replacing multi-line comments with direct `core.setFailed` calls, embedding the relevant messages and label data directly into the failure output. 
* Updated the `typeLabels` array to include more descriptive labels prefixed with `type:` (e.g., `type: bug`, `type: improvement`) for better categorization and searchability.
=> [infra] Remove commentHandler and change label names

packages/bundle-size-checker/src/uploadSnapshot.js
Sanitize tag values before uploading
=> [infra] Update uploadSnapshot.js

.github/workflows/ci.yml, .github/workflows/publish.yml, package.json, pnpm-lock.yaml, scripts/publish.mjs
* publish npm packages from master branch if their current versions are unpublished.
* publish canary version of all packages for every master branch commit
* add npm provenance
this allows us to set up renovatebot on dependent repos to bump internal dependencies on every change
=> [infra] Automate publishing

.github/workflows/publish.yml
It needs to be able to push tags to mark commits that have been published as canary
=> [infra] Set write permission in publish action

packages/babel-plugin-display-name/src/index.js, packages/babel-plugin-display-name/src/index.test.js
Fixes https://github.com/mui/mui-x/issues/18174
It tries assigning `displayName` to a variable, even if it's undefined.
https://github.com/mui/mui-x/blob/9ba4aa36e4e69d55d8187b2297e2cf9b41337800/packages/x-data-grid-premium/src/components/GridPremiumToolbar.tsx#L43-L53
In this example, `additionalExportMenuItems` is not a React component, but a function that returns a JSX Element and is called directly.
So `displayName` is not necessary here.
It seems impossible to know whether this function is a React component, but at least we can make sure that both paths of a ternary operator are functions.
=> Do not assign `displayName` to non-functions

scripts/publish.mjs
* `semver.inc()` also increments patch when incrementing prerelease if necessary, so avoid double patch increment
* Make sure `latestCanaryVersion` gets passed correctly, remove outdated check against base version. Instead use `semver` to compare and select base version to start incrementing from.
=> [infra] Some fixes to auto canary publishing

packages/babel-plugin-resolve-imports/index.js
Necessary if we want to fix the type declarations for .mjs files. For https://github.com/mui/mui-x/issues/17503#issuecomment-3031634156
=> [infra] Add mjs and mts to import resolver extensions

renovate/default.json
This config will be extended in the downstream repos using -
```json
{
"extends": ["github>mui/mui-public//renovate/default"]
}
```
See - https://docs.renovatebot.com/config-presets/#github
Companion PRs -
1. https://github.com/mui/material-ui/pull/46483
2. https://github.com/mui/mui-x/pull/18683
3. https://github.com/mui/base-ui/pull/2257
=> [code-infra] Shareable renovate preset

.github/workflows/ci-base.yml
Companion PR that has the actual fix - https://github.com/mui/material-ui/pull/46563
which removed `publishConfig.directory` from the output package.json for this to work.
Note: This PR should be merged only after all repos are migrated to use latest monorepo once the above PR is merged.
=> [infra] Use pnpm pack to fix catalog resolution

packages/code-infra/src/cli/cmdSetVersionOverrides.mjs, packages/code-infra/src/cli/index.mjs, packages/code-infra/src/cli/pnpm.mjs
Porting https://github.com/mui/material-ui/blob/348eb570a48100c0024b9d35f07be6a30efcded0/scripts/useReactVersion.mjs
We will inverse the flow though to first install, then run this script. The total runtime is a few seconds slower but the DX is a lot better.
=> Add version overrides script

packages/code-infra/src/cli/cmdSetVersionOverrides.mjs, packages/code-infra/src/cli/pnpm.mjs
`pnpm info <pkg> version` can return multiple
Also find scheduler dependency based on resolved react-dom
=> [infra] Fix when version command returns array

packages/bundle-size-checker/src/viteBuilder.js, test/bundle-size/package.json
Can't reproduce reliably, but it looks like sometimes the vite build promise resolves while not all fs operations are fully flushed. ~Testing this hypothesis by adding a short waiting mechanism.~ We can just operate on the vite output instead of trying to read the file system. All necessary info is available.
Example workflow: https://app.circleci.com/pipelines/github/mui/material-ui/158165/workflows/a4b52c56-c4c0-46f5-b8b5-fd63dee00c5f/jobs/846106
=> [code-infra] Use vite output ti calculate sizes

packages/bundle-size-checker/src/uploadSnapshot.js
Fix https://github.com/mui/mui-public/security/code-scanning/35
Before:
```js
','.replace(/[^a-zA-Z0-9 +-=.:/@]+/g, '_') => ','
```
After:
```jsx
','.replace(/[^a-zA-Z0-9 +\-=.:/@]+/g, '_') => '_'
```
The ASCII table: https://www.ascii-code.com/. A fun read on this one: https://web.archive.org/web/20221222190604/https://pboyd.io/posts/comma-dash-dot/.
=> [internal] Fix sanitizeS3TagString()

apps/code-infra-dashboard/package.json, pnpm-lock.yaml
This should fix a few problems:
1. When running `pnpm dev` (`pnpm --package netlify-cli@15 dlx netlify dev`), it returns errors
2. netlify-cli depends on packages with security issues, e.g. https://github.com/mui/mui-public/security/dependabot/119
3. We install Netlify CLI 20 but we use v15
4. v15 is 2 years old: https://www.npmjs.com/package/netlify-cli/v/15.0.0.
Side notes:
- https://www.npmjs.com/package/netlify-cli?activeTab=versions illustrate why we can't publish to npm each commit, I can't load the page, it crashes
- This PR should fix most of the security flags in https://github.com/mui/mui-public/security/dependabot. With [the few PRs](https://github.com/mui/mui-public/issues?q=state%3Aopen%20label%3Asecurity%20is%3Apr) I have opened, we should get to a much lower number than 50 …
=> [internal] Fix Netlify CLI

.github/workflows/branch-monitor.yml, .github/workflows/ci-base.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml
See https://github.com/mui/mui-public/security/code-scanning there are a bunch of security alerts. This PR fixes the false-positives of this kind: https://github.com/mui/mui-public/security/code-scanning/26. Our GitHub organization is configured with https://github.com/organizations/mui/settings/actions
so this PR doesn't help with security directly, what it helps with is increase the signal-to-noise ratio, so we can only have true-positives.
For the root problem, there is already: https://github.com/ossf/scorecard/issues/2556.
=> [internal] Enforce GITHUB_TOKEN default read only permission

packages/code-infra/src/cli/cmdListWorkspaces.mjs, packages/code-infra/src/cli/cmdPublish.mjs, packages/code-infra/src/cli/cmdPublishCanary.mjs, packages/code-infra/src/cli/pnpm.mjs
We would error when not called with --public-only as some of our workspaces are unnamed. Instead of the name/vrsion check, we treat unnamed and unversiononed packages as private, which is what npm does as well
=> [code-infra] Fix error on `list-workspaces` command

.circleci/config.yml, .github/workflows/ci-base.yml, .github/workflows/ci.yml, apps/code-infra-dashboard/netlify.toml, package.json, pnpm-workspace.yaml, update-netlify-ignore.mjs
We can safely start with this repo and eventually add this to other repos as well.
https://docs.renovatebot.com/configuration-options/#constraints
=> [code-infra] Make engine version requirement strict

.github/workflows/scripts/prs/checkTypeLabel.js
Why: https://github.com/mui/material-ui/pulls?q=is%3Apr+label%3Aduplicate+is%3Aclosed.
A step toward solving #206.
=> [support-infra] Ignore duplicate for the type label

packages/code-infra/src/cli/cmdBuild.mjs
https://github.com/mui/base-ui/pull/2566#pullrequestreview-3148172478 "The is anyways removed from the published package.json", it's not, proof: https://unpkg.com/@base-ui-components/react@1.0.0-beta.2/package.json, but now, it will be :).
You can test this like this:
```diff
diff --git a/packages/docs-infra/package.json b/packages/docs-infra/package.json
index a0648f1..8b2ac35 100644
--- a/packages/docs-infra/package.json
+++ b/packages/docs-infra/package.json
@@ -1,6 +1,7 @@
{
"name": "@mui/internal-docs-infra",
"version": "0.1.0",
+  "private": false,
"author": "MUI Team",
"description": "MUI Infra - internal documentation creation tools.",
"keywords": [
```
`pnpm --filter ./packages/docs-infra build`
=> [code-infra] Throw if private: false is set

.github/workflows/issue-status-label-handler.yml, .github/workflows/no-response.yml
I think mui-public should set the standard of what are our GitHub Actions. We tried this new flow for mui-x, it seems to work well, so let's update the source of truth.
One of #487
=> [support-infra] Update status labels GitHub Actions

.github/workflows/scripts/issues/addClosingMessage.js
This PR tries to solve the corporate vibe mentioned in #480. The proposed solution is to shift the terminology from Customer Support jargon to wording something any person could understand. I assume that with this, there are no downsides to enabling it in Joy UI, Base UI, etc.
See https://github.com/mui/mui-x/issues/15674#issuecomment-3209158790 as the new experience that this PR proposes.
=> [support-infra] Un-enterprise the CSAT flow

packages/code-infra/src/cli/cmdBuild.mjs
This will help with the new `docs-infra` [package](https://github.com/mui/mui-public/pull/379) where `turbopack` looks for the `default` condition when importing using 
a string path in next.config.
When both cjs and esm builds are present -
```txt
"./*": {
"require": {
"types": "./*/index.d.ts",
"default": "./*/index.js"
},
"default": {
"types": "./esm/*/index.d.ts",
"default": "./esm/*/index.js"
}
},
```
Only cjs build
```txt
"exports": {
"./package.json": "./package.json",
"./*": {
"default": {
"types": "./*/index.d.ts",
"default": "./*/index.js"
}
}
}
```
Only ESM build
```txt
"exports": {
"./package.json": "./package.json",
"./*": {
"default": {
"types": "./esm/*/index.d.ts",
"default": "./esm/*/index.js"
}
}
}
```
=> [infra] Add `default` condition to the built package.json

.github/workflows/ci.yml
Problem:
- it's running twice for each pull request
- it's not running for renovate pull requests, see https://github.com/mui/mui-public/pull/631
Solution:
- add the `pull_request` trigger
- configure `branches` for the `push` trigger instead of ignore
Supplying the `next` and `v*.x` release branches as well. It doesn't do much on this repo, but will propagate this to other repos and that way it can stay the same across the org. I noticed at least `mui/material-ui` suffers from the same problem
=> [code-infra] Improve ci workflow trigger

.github/workflows/scripts/issues/addClosingMessage.js
This adds breaks to the separator line to prevent github markdown rendering the first paragraph as `h1`
=> [support-infra] Fix the formatting of closed issue message

renovate/base.json, renovate/default.json
create a preset we use to create package rules before any preset. add a dev dependencies.
To note: this can cause issues when a dependency is both a dev and normal dependency somewhere.
=> [code-infra] Create dev dependencies group

packages/code-infra/src/eslint/material-ui/config.mjs
This caused a few issues on the Scheduler and I'm surprised it's not more problematic on Base UI (unless they patch their config to add it).
The `useIsoLayoutEffect` is the new name of the `useEnhancedEffect` hook in the Base UI utils package.
=> [code-infra] Make sure `useIsoLayoutEffect` is tested by `react-hooks/exhaustive-deps`

renovate/default.json
Mainly experimenting here to stop renovate from updating the value of `node-version` in github actions.
Fixes #643
Also consolidation Vite packages with a preset.
=> [code-infra] Try to disable node-version updates in github actions

renovate/default.json
I saw vite being grouped into the [devdependencies group](https://github.com/mui/mui-public/pull/701), but they should be in "vite & vitest"
I believe we need separate rules as to avoid the combined rules from making the group too narrow
=> [code-infra] Widen vite group

renovate/default.json
Minimum 3 days, to exceed the unpublish period npm uses. Should also mitigate a bit supply-chain attacks
=> [code-infra] Prevent PRs until released longer than 3 days

packages/docs-infra/src/CodeHighlighter/CodeHighlighterClient.tsx
`requestIdleCallback` is not supported by Safari, so we need to check for it. Otherwise we get this error:
```
TypeError: window.requestIdleCallback is not a function. (In 'window.requestIdleCallback(function(){tC(!0)})', 'window.requestIdleCallback' is undefined)
```
=> [docs-infra] Check for requestIdleCallback

packages/bundle-size-checker/src/builder.js, packages/bundle-size-checker/src/cli.js, packages/bundle-size-checker/src/strings.js, packages/bundle-size-checker/src/worker.js, pnpm-lock.yaml
Seeing vite trying to operate on non-existing folders sometimes: https://app.circleci.com/pipelines/github/mui/material-ui/160919/workflows/6eb98677-9fd6-4adf-8247-74d9adc186c9/jobs/859195
Use a flat file structure to prevent vite from poisoning itself when it empties a parent a folder containing already finsihed builds. We can just replace slashes with underscores to achieve this.
=> [code-infra] Fix bundles nested file paths

packages/docs-infra/package.json, packages/docs-infra/src/useCode/useCode.ts, packages/docs-infra/src/useCode/useFileNavigation.tsx, packages/docs-infra/src/useCode/useVariantSelection.test.ts, packages/docs-infra/src/useCode/useVariantSelection.ts, packages/docs-infra/src/useCode/user.spec.ts, pnpm-lock.yaml
When navigating to a url `/components/checkbox#hero:index.module.css` it was being replaced with `/components/checkbox#hero:tailwind:index.tsx` after the first render if `Tailwind` was preferred by the user. The URL hash should be prioritized in this case. Especially because the Tailwind variant doesn't even have a `.module.css` file so the user is shown `index.tsx`.
I've verified this works directly in base-ui: https://deploy-preview-2443--base-ui.netlify.app/react/components/checkbox#hero:index.module.css if you set tailwind as a preference and click that URL again, it should still display the CSS Modules variant
=> [docs-infra] Update localStorage logic to prioritize URL hash over stored preferences
